---
x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: ./docker/airflow/Dockerfile.airflow
  env_file:
    - ./env.minio.example
  environment:
    &airflow-common-env
    AIRFLOW__CORE__XCOM_BACKEND: airflow.models.xcom.BaseXCom
    AIRFLOW_CONN_SPARK_DEFAULT: spark://spark-master:7077
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: 'HNBnrrvFVSEGnYVgyMse1HSg7cSJpP3cuyYrkjxIN70='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__CORE__ENABLE_XCOM_PICKLING: 'false'
    AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: 'true'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Sao_Paulo
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-webserver:8080/execution/'
    TZ: America/Sao_Paulo
    # PySpark and Java environment
    SPARK_HOME: /opt/spark
    SPARK_MASTER_URL: spark://spark-master:7077
  depends_on:
    - postgres
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./requirements.txt:/opt/airflow/requirements.txt
    - ./ivy:/home/airflow/.ivy2
    - ./events:/opt/spark/events
    - ./spark-logs:/opt/spark/logs
  networks:
    - lakehouse-network

---
x-spark-common:
  &spark-common
  build:
    context: .
    dockerfile: ./docker/spark/Dockerfile.spark
  env_file:
    - ./env.minio.example
  environment:
    &spark-worker-common-env
    SPARK_MASTER_URL: spark://spark-master:7077
    SPARK_RPC_AUTHENTICATION_ENABLED: no
    SPARK_RPC_ENCRYPTION_ENABLED: no
    SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED: no
    SPARK_SSL_ENABLED: no
  volumes:
    - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    - ./data:/app/data:ro
    - ./events:/opt/spark/events
    - ./spark-logs:/opt/spark/logs
  networks:
    - lakehouse-network
  restart: unless-stopped

services:

  nessie:
    image: ghcr.io/projectnessie/nessie:0.91.0
    container_name: nessie
    depends_on: 
      - minio
    environment:
      QUARKUS_HTTP_PORT: 19120
    ports:
      - "19120:19120"
    volumes:
      - nessie-data:/var/nessie/data
    networks:
      - lakehouse-network

  trino:
    image: trinodb/trino:435
    env_file:
      - ./env.minio.example
    container_name: trino
    depends_on: 
      - nessie
      - minio
      #- iceberg-rest
    ports:
      - "8082:8080"
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      CATALOG_MANAGEMENT: dynamic
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog
      - ./trino/etc/config.properties:/etc/trino/config.properties
    networks:
      - lakehouse-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/v1/info"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always

  # Apache Airflow
  airflow-webserver:
    <<: *airflow-common
    depends_on:
      - airflow-init
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    depends_on:
      - airflow-init
    command: scheduler
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - airflow-init

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - airflow-init

  airflow-init:
    build:
      context: .
      dockerfile: ./docker/airflow/Dockerfile.airflow
    depends_on:
      - postgres
    environment:
      <<: *airflow-common-env
      AIRFLOW__CORE__XCOM_BACKEND: airflow.models.xcom.BaseXCom
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-admin}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-admin}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./requirements.txt:/opt/airflow/requirements.txt  
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.org --password admin"
    restart: on-failure
    networks:
      - lakehouse-network

  # PostgreSQL for Airflow metadata
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - lakehouse-network

  # MinIO for local S3-compatible storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ./env.minio.example
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    networks:
      - lakehouse-network

  # MinIO Client for setup (bucket creation and policies)
  minio-client:
    image: minio/mc:latest
    container_name: minio-client-airflow
    depends_on:
      - minio
    env_file:
      - ./env.minio.example
    entrypoint: ["sh", "-c", "/scripts/minio-init.sh"]
    volumes:
      - ./scripts/minio-init.sh:/scripts/minio-init.sh
    networks:
      - lakehouse-network

  # Spark Master
  spark-master:
    <<: *spark-common
    container_name: spark-master
    depends_on:
      - minio
      - minio-client
      #- iceberg-rest
      - nessie
    environment:
      SPARK_MODE: master
    ports:
      - "8081:8080"  # Spark Master UI (8080 inside container)
      - "7077:7077"  # Spark Master RPC
    entrypoint: >
      sh -c "
        sleep 30 &&
        /opt/spark/sbin/start-master.sh &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.master.Master-*.out
      "

  # Spark Worker 1
  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      <<: *spark-worker-common-env
      SPARK_MODE: worker
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    entrypoint: >
      sh -c "
        sleep 35 &&
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.worker.Worker-*.out
      "

  # Spark Worker 2
  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    entrypoint: >
      sh -c "
        sleep 35 &&
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.worker.Worker-*.out
      "

  # Spark Worker 3
  spark-worker-3:
    <<: *spark-common
    container_name: spark-worker-3
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1
    entrypoint: >
      sh -c "
        sleep 35 &&
        /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
        tail -f /opt/spark/logs/spark-*-org.apache.spark.deploy.worker.Worker-*.out
      "

  spark-history-server:
    <<: *spark-common
    container_name: spark-history-server
    entrypoint: /bin/bash
    command: -c "/opt/spark/sbin/start-history-server.sh; tail -f /dev/null"
    ports:
      - '18080:18080'

#  # Iceberg REST Catalog
#  iceberg-rest:
#    image: apache/iceberg-rest-fixture
#    container_name: iceberg-rest
#    networks:
#      - lakehouse-network
#    ports:
#      - 8181:8181
#    environment:
#      - AWS_ACCESS_KEY_ID=admin
#      - AWS_SECRET_ACCESS_KEY=admin123
#      - AWS_REGION=us-east-1
#      - CATALOG_WAREHOUSE=s3a://warehouse/
#      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
#      - CATALOG_S3_ENDPOINT=http://minio:9000
#      - CATALOG_S3_PATH_STYLE_ACCESS=true 
#      - CATALOG_S3_REGION=us-east-1
#      - MINIO_SERVER_URL=http://minio:9000
#    volumes:
#      - iceberg-catalog-data:/var/iceberg/catalog
#    depends_on:
#      - minio

volumes:
  postgres-db-volume:
  minio-data:
  nessie-data:
#  iceberg-catalog-data:

networks:
  lakehouse-network: